<?php
$data = array (
  2 => 
  array (
    'cat_id' => '2',
    'cat_name' => '生鲜食品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '5',
    'sort_order' => '1',
    'has_children' => '8',
    'goods_num' => 0,
    'level' => 0,
    'id' => '2',
    'name' => '生鲜食品',
  ),
  16 => 
  array (
    'cat_id' => '16',
    'cat_name' => '海鲜水产',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => '4',
    'level' => 1,
    'id' => '16',
    'name' => '海鲜水产',
  ),
  71 => 
  array (
    'cat_id' => '71',
    'cat_name' => '蟹/贝',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '71',
    'name' => '蟹/贝',
  ),
  68 => 
  array (
    'cat_id' => '68',
    'cat_name' => '参鲍',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '68',
    'name' => '参鲍',
  ),
  69 => 
  array (
    'cat_id' => '69',
    'cat_name' => '鱼',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '69',
    'name' => '鱼',
  ),
  70 => 
  array (
    'cat_id' => '70',
    'cat_name' => '虾',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '70',
    'name' => '虾',
  ),
  20 => 
  array (
    'cat_id' => '20',
    'cat_name' => '茄果类',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '20',
    'name' => '茄果类',
  ),
  17 => 
  array (
    'cat_id' => '17',
    'cat_name' => '蛋制品',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => '1',
    'level' => 1,
    'id' => '17',
    'name' => '蛋制品',
  ),
  72 => 
  array (
    'cat_id' => '72',
    'cat_name' => '松花蛋/咸鸭蛋',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '72',
    'name' => '松花蛋/咸鸭蛋',
  ),
  73 => 
  array (
    'cat_id' => '73',
    'cat_name' => '鸡蛋',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '73',
    'name' => '鸡蛋',
  ),
  21 => 
  array (
    'cat_id' => '21',
    'cat_name' => '菌菇类',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '21',
    'name' => '菌菇类',
  ),
  18 => 
  array (
    'cat_id' => '18',
    'cat_name' => '叶菜类',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => '1',
    'level' => 1,
    'id' => '18',
    'name' => '叶菜类',
  ),
  77 => 
  array (
    'cat_id' => '77',
    'cat_name' => '西兰花',
    'measure_unit' => '',
    'parent_id' => '18',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '77',
    'name' => '西兰花',
  ),
  74 => 
  array (
    'cat_id' => '74',
    'cat_name' => '生菜',
    'measure_unit' => '',
    'parent_id' => '18',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '74',
    'name' => '生菜',
  ),
  75 => 
  array (
    'cat_id' => '75',
    'cat_name' => '菠菜',
    'measure_unit' => '',
    'parent_id' => '18',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '75',
    'name' => '菠菜',
  ),
  76 => 
  array (
    'cat_id' => '76',
    'cat_name' => '圆椒',
    'measure_unit' => '',
    'parent_id' => '18',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '76',
    'name' => '圆椒',
  ),
  15 => 
  array (
    'cat_id' => '15',
    'cat_name' => '精品肉类',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => '1',
    'level' => 1,
    'id' => '15',
    'name' => '精品肉类',
  ),
  67 => 
  array (
    'cat_id' => '67',
    'cat_name' => '牛肉',
    'measure_unit' => '',
    'parent_id' => '15',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '67',
    'name' => '牛肉',
  ),
  64 => 
  array (
    'cat_id' => '64',
    'cat_name' => '羊肉',
    'measure_unit' => '',
    'parent_id' => '15',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '64',
    'name' => '羊肉',
  ),
  65 => 
  array (
    'cat_id' => '65',
    'cat_name' => '禽类',
    'measure_unit' => '',
    'parent_id' => '15',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '65',
    'name' => '禽类',
  ),
  66 => 
  array (
    'cat_id' => '66',
    'cat_name' => '猪肉',
    'measure_unit' => '',
    'parent_id' => '15',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '66',
    'name' => '猪肉',
  ),
  22 => 
  array (
    'cat_id' => '22',
    'cat_name' => '进口生鲜',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '22',
    'name' => '进口生鲜',
  ),
  19 => 
  array (
    'cat_id' => '19',
    'cat_name' => '根茎类',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 1,
    'id' => '19',
    'name' => '根茎类',
  ),
  1 => 
  array (
    'cat_id' => '1',
    'cat_name' => '酒水饮料',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '7',
    'goods_num' => 0,
    'level' => 0,
    'id' => '1',
    'name' => '酒水饮料',
  ),
  29 => 
  array (
    'cat_id' => '29',
    'cat_name' => '红酒',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => '1',
    'level' => 1,
    'id' => '29',
    'name' => '红酒',
  ),
  81 => 
  array (
    'cat_id' => '81',
    'cat_name' => '白兰地',
    'measure_unit' => '',
    'parent_id' => '29',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '81',
    'name' => '白兰地',
  ),
  82 => 
  array (
    'cat_id' => '82',
    'cat_name' => '威士忌',
    'measure_unit' => '',
    'parent_id' => '29',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '82',
    'name' => '威士忌',
  ),
  26 => 
  array (
    'cat_id' => '26',
    'cat_name' => '啤酒',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '26',
    'name' => '啤酒',
  ),
  23 => 
  array (
    'cat_id' => '23',
    'cat_name' => '白酒',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => '2',
    'level' => 1,
    'id' => '23',
    'name' => '白酒',
  ),
  83 => 
  array (
    'cat_id' => '83',
    'cat_name' => '五粮液',
    'measure_unit' => '',
    'parent_id' => '23',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '83',
    'name' => '五粮液',
  ),
  84 => 
  array (
    'cat_id' => '84',
    'cat_name' => '泸州老窖',
    'measure_unit' => '',
    'parent_id' => '23',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '84',
    'name' => '泸州老窖',
  ),
  85 => 
  array (
    'cat_id' => '85',
    'cat_name' => '茅台',
    'measure_unit' => '',
    'parent_id' => '23',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '85',
    'name' => '茅台',
  ),
  27 => 
  array (
    'cat_id' => '27',
    'cat_name' => '其他酒品',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => '1',
    'level' => 1,
    'id' => '27',
    'name' => '其他酒品',
  ),
  80 => 
  array (
    'cat_id' => '80',
    'cat_name' => '养生酒',
    'measure_unit' => '',
    'parent_id' => '27',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '80',
    'name' => '养生酒',
  ),
  78 => 
  array (
    'cat_id' => '78',
    'cat_name' => '其他品牌',
    'measure_unit' => '',
    'parent_id' => '27',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '78',
    'name' => '其他品牌',
  ),
  79 => 
  array (
    'cat_id' => '79',
    'cat_name' => '黄酒',
    'measure_unit' => '',
    'parent_id' => '27',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '79',
    'name' => '黄酒',
  ),
  24 => 
  array (
    'cat_id' => '24',
    'cat_name' => '葡萄酒',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 1,
    'id' => '24',
    'name' => '葡萄酒',
  ),
  28 => 
  array (
    'cat_id' => '28',
    'cat_name' => '饮料/水',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 1,
    'id' => '28',
    'name' => '饮料/水',
  ),
  25 => 
  array (
    'cat_id' => '25',
    'cat_name' => '洋酒',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 1,
    'id' => '25',
    'name' => '洋酒',
  ),
  5 => 
  array (
    'cat_id' => '5',
    'cat_name' => '粮油副食',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 0,
    'id' => '5',
    'name' => '粮油副食',
  ),
  32 => 
  array (
    'cat_id' => '32',
    'cat_name' => '厨房调料',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => '1',
    'level' => 1,
    'id' => '32',
    'name' => '厨房调料',
  ),
  94 => 
  array (
    'cat_id' => '94',
    'cat_name' => '调味油/汁',
    'measure_unit' => '',
    'parent_id' => '32',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '94',
    'name' => '调味油/汁',
  ),
  95 => 
  array (
    'cat_id' => '95',
    'cat_name' => '酱油/醋',
    'measure_unit' => '',
    'parent_id' => '32',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '95',
    'name' => '酱油/醋',
  ),
  33 => 
  array (
    'cat_id' => '33',
    'cat_name' => '南北干货',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '33',
    'name' => '南北干货',
  ),
  30 => 
  array (
    'cat_id' => '30',
    'cat_name' => '食用油',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => '2',
    'level' => 1,
    'id' => '30',
    'name' => '食用油',
  ),
  90 => 
  array (
    'cat_id' => '90',
    'cat_name' => '礼盒',
    'measure_unit' => '',
    'parent_id' => '30',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '90',
    'name' => '礼盒',
  ),
  87 => 
  array (
    'cat_id' => '87',
    'cat_name' => '菜仔油',
    'measure_unit' => '',
    'parent_id' => '30',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '87',
    'name' => '菜仔油',
  ),
  88 => 
  array (
    'cat_id' => '88',
    'cat_name' => '花生油',
    'measure_unit' => '',
    'parent_id' => '30',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '88',
    'name' => '花生油',
  ),
  89 => 
  array (
    'cat_id' => '89',
    'cat_name' => '橄榄油',
    'measure_unit' => '',
    'parent_id' => '30',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '89',
    'name' => '橄榄油',
  ),
  86 => 
  array (
    'cat_id' => '86',
    'cat_name' => '其他食用油',
    'measure_unit' => '',
    'parent_id' => '30',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '86',
    'name' => '其他食用油',
  ),
  34 => 
  array (
    'cat_id' => '34',
    'cat_name' => '方便速食',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '34',
    'name' => '方便速食',
  ),
  31 => 
  array (
    'cat_id' => '31',
    'cat_name' => '米面杂粮',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => '1',
    'level' => 1,
    'id' => '31',
    'name' => '米面杂粮',
  ),
  93 => 
  array (
    'cat_id' => '93',
    'cat_name' => '意大利面',
    'measure_unit' => '',
    'parent_id' => '31',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '93',
    'name' => '意大利面',
  ),
  91 => 
  array (
    'cat_id' => '91',
    'cat_name' => '面粉/面条',
    'measure_unit' => '',
    'parent_id' => '31',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '91',
    'name' => '面粉/面条',
  ),
  92 => 
  array (
    'cat_id' => '92',
    'cat_name' => '大米',
    'measure_unit' => '',
    'parent_id' => '31',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '92',
    'name' => '大米',
  ),
  35 => 
  array (
    'cat_id' => '35',
    'cat_name' => '调味品',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '35',
    'name' => '调味品',
  ),
  11 => 
  array (
    'cat_id' => '11',
    'cat_name' => '蔬菜水果',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 0,
    'id' => '11',
    'name' => '蔬菜水果',
  ),
  42 => 
  array (
    'cat_id' => '42',
    'cat_name' => '精选蔬菜',
    'measure_unit' => '',
    'parent_id' => '11',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => '2',
    'level' => 1,
    'id' => '42',
    'name' => '精选蔬菜',
  ),
  99 => 
  array (
    'cat_id' => '99',
    'cat_name' => '甘蓝',
    'measure_unit' => '',
    'parent_id' => '42',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '99',
    'name' => '甘蓝',
  ),
  100 => 
  array (
    'cat_id' => '100',
    'cat_name' => '胡萝卜',
    'measure_unit' => '',
    'parent_id' => '42',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '100',
    'name' => '胡萝卜',
  ),
  101 => 
  array (
    'cat_id' => '101',
    'cat_name' => '黄瓜',
    'measure_unit' => '',
    'parent_id' => '42',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '101',
    'name' => '黄瓜',
  ),
  43 => 
  array (
    'cat_id' => '43',
    'cat_name' => '进口水果',
    'measure_unit' => '',
    'parent_id' => '11',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => '1',
    'level' => 1,
    'id' => '43',
    'name' => '进口水果',
  ),
  103 => 
  array (
    'cat_id' => '103',
    'cat_name' => '菠萝蜜',
    'measure_unit' => '',
    'parent_id' => '43',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '103',
    'name' => '菠萝蜜',
  ),
  104 => 
  array (
    'cat_id' => '104',
    'cat_name' => '奇异果',
    'measure_unit' => '',
    'parent_id' => '43',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '104',
    'name' => '奇异果',
  ),
  102 => 
  array (
    'cat_id' => '102',
    'cat_name' => '火龙果',
    'measure_unit' => '',
    'parent_id' => '43',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '102',
    'name' => '火龙果',
  ),
  44 => 
  array (
    'cat_id' => '44',
    'cat_name' => '国产水果',
    'measure_unit' => '',
    'parent_id' => '11',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => '2',
    'level' => 1,
    'id' => '44',
    'name' => '国产水果',
  ),
  106 => 
  array (
    'cat_id' => '106',
    'cat_name' => '苹果',
    'measure_unit' => '',
    'parent_id' => '44',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '106',
    'name' => '苹果',
  ),
  107 => 
  array (
    'cat_id' => '107',
    'cat_name' => '雪梨',
    'measure_unit' => '',
    'parent_id' => '44',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '107',
    'name' => '雪梨',
  ),
  105 => 
  array (
    'cat_id' => '105',
    'cat_name' => '水果礼盒',
    'measure_unit' => '',
    'parent_id' => '44',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '105',
    'name' => '水果礼盒',
  ),
  41 => 
  array (
    'cat_id' => '41',
    'cat_name' => '有机蔬菜',
    'measure_unit' => '',
    'parent_id' => '11',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => '2',
    'level' => 1,
    'id' => '41',
    'name' => '有机蔬菜',
  ),
  96 => 
  array (
    'cat_id' => '96',
    'cat_name' => '西红柿',
    'measure_unit' => '',
    'parent_id' => '41',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '96',
    'name' => '西红柿',
  ),
  97 => 
  array (
    'cat_id' => '97',
    'cat_name' => '韭菜',
    'measure_unit' => '',
    'parent_id' => '41',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '97',
    'name' => '韭菜',
  ),
  98 => 
  array (
    'cat_id' => '98',
    'cat_name' => '青菜',
    'measure_unit' => '',
    'parent_id' => '41',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '98',
    'name' => '青菜',
  ),
  9 => 
  array (
    'cat_id' => '9',
    'cat_name' => '休闲食品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '5',
    'goods_num' => '1',
    'level' => 0,
    'id' => '9',
    'name' => '休闲食品',
  ),
  39 => 
  array (
    'cat_id' => '39',
    'cat_name' => '肉干肉脯/豆干',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 1,
    'id' => '39',
    'name' => '肉干肉脯/豆干',
  ),
  122 => 
  array (
    'cat_id' => '122',
    'cat_name' => '猪肉脯',
    'measure_unit' => '',
    'parent_id' => '39',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '122',
    'name' => '猪肉脯',
  ),
  123 => 
  array (
    'cat_id' => '123',
    'cat_name' => '牛肉粒',
    'measure_unit' => '',
    'parent_id' => '39',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '123',
    'name' => '牛肉粒',
  ),
  124 => 
  array (
    'cat_id' => '124',
    'cat_name' => '猪肉干',
    'measure_unit' => '',
    'parent_id' => '39',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '124',
    'name' => '猪肉干',
  ),
  121 => 
  array (
    'cat_id' => '121',
    'cat_name' => '牛肉干',
    'measure_unit' => '',
    'parent_id' => '39',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '121',
    'name' => '牛肉干',
  ),
  36 => 
  array (
    'cat_id' => '36',
    'cat_name' => '休闲零食',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 1,
    'id' => '36',
    'name' => '休闲零食',
  ),
  112 => 
  array (
    'cat_id' => '112',
    'cat_name' => '坚果炒货',
    'measure_unit' => '',
    'parent_id' => '36',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '112',
    'name' => '坚果炒货',
  ),
  109 => 
  array (
    'cat_id' => '109',
    'cat_name' => '枣类',
    'measure_unit' => '',
    'parent_id' => '36',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '109',
    'name' => '枣类',
  ),
  110 => 
  array (
    'cat_id' => '110',
    'cat_name' => '蜜饯',
    'measure_unit' => '',
    'parent_id' => '36',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '110',
    'name' => '蜜饯',
  ),
  111 => 
  array (
    'cat_id' => '111',
    'cat_name' => '肉类零食',
    'measure_unit' => '',
    'parent_id' => '36',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '111',
    'name' => '肉类零食',
  ),
  108 => 
  array (
    'cat_id' => '108',
    'cat_name' => '果冻',
    'measure_unit' => '',
    'parent_id' => '36',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '108',
    'name' => '果冻',
  ),
  40 => 
  array (
    'cat_id' => '40',
    'cat_name' => '鱿鱼丝/鱼干',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 1,
    'id' => '40',
    'name' => '鱿鱼丝/鱼干',
  ),
  128 => 
  array (
    'cat_id' => '128',
    'cat_name' => '鱿鱼仔',
    'measure_unit' => '',
    'parent_id' => '40',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '128',
    'name' => '鱿鱼仔',
  ),
  125 => 
  array (
    'cat_id' => '125',
    'cat_name' => '鱿鱼足',
    'measure_unit' => '',
    'parent_id' => '40',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '125',
    'name' => '鱿鱼足',
  ),
  129 => 
  array (
    'cat_id' => '129',
    'cat_name' => '鱿鱼片',
    'measure_unit' => '',
    'parent_id' => '40',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '129',
    'name' => '鱿鱼片',
  ),
  126 => 
  array (
    'cat_id' => '126',
    'cat_name' => '鱿鱼丝',
    'measure_unit' => '',
    'parent_id' => '40',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '126',
    'name' => '鱿鱼丝',
  ),
  127 => 
  array (
    'cat_id' => '127',
    'cat_name' => '墨鱼/乌贼',
    'measure_unit' => '',
    'parent_id' => '40',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '127',
    'name' => '墨鱼/乌贼',
  ),
  37 => 
  array (
    'cat_id' => '37',
    'cat_name' => '糖果',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 1,
    'id' => '37',
    'name' => '糖果',
  ),
  115 => 
  array (
    'cat_id' => '115',
    'cat_name' => '软糖',
    'measure_unit' => '',
    'parent_id' => '37',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '115',
    'name' => '软糖',
  ),
  116 => 
  array (
    'cat_id' => '116',
    'cat_name' => '棒棒糖',
    'measure_unit' => '',
    'parent_id' => '37',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '116',
    'name' => '棒棒糖',
  ),
  113 => 
  array (
    'cat_id' => '113',
    'cat_name' => '创意喜糖',
    'measure_unit' => '',
    'parent_id' => '37',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '113',
    'name' => '创意喜糖',
  ),
  114 => 
  array (
    'cat_id' => '114',
    'cat_name' => '口香糖',
    'measure_unit' => '',
    'parent_id' => '37',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '114',
    'name' => '口香糖',
  ),
  38 => 
  array (
    'cat_id' => '38',
    'cat_name' => '巧克力',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 1,
    'id' => '38',
    'name' => '巧克力',
  ),
  119 => 
  array (
    'cat_id' => '119',
    'cat_name' => '松露巧克力',
    'measure_unit' => '',
    'parent_id' => '38',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '119',
    'name' => '松露巧克力',
  ),
  120 => 
  array (
    'cat_id' => '120',
    'cat_name' => '黑巧克力',
    'measure_unit' => '',
    'parent_id' => '38',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '120',
    'name' => '黑巧克力',
  ),
  117 => 
  array (
    'cat_id' => '117',
    'cat_name' => '夹心巧克力',
    'measure_unit' => '',
    'parent_id' => '38',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '117',
    'name' => '夹心巧克力',
  ),
  118 => 
  array (
    'cat_id' => '118',
    'cat_name' => '白巧克力',
    'measure_unit' => '',
    'parent_id' => '38',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '118',
    'name' => '白巧克力',
  ),
  12 => 
  array (
    'cat_id' => '12',
    'cat_name' => '奶类食品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '5',
    'goods_num' => '1',
    'level' => 0,
    'id' => '12',
    'name' => '奶类食品',
  ),
  48 => 
  array (
    'cat_id' => '48',
    'cat_name' => '有机奶',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '48',
    'name' => '有机奶',
  ),
  45 => 
  array (
    'cat_id' => '45',
    'cat_name' => '进口奶品',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 1,
    'id' => '45',
    'name' => '进口奶品',
  ),
  49 => 
  array (
    'cat_id' => '49',
    'cat_name' => '原料奶',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '49',
    'name' => '原料奶',
  ),
  46 => 
  array (
    'cat_id' => '46',
    'cat_name' => '国产奶品',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '46',
    'name' => '国产奶品',
  ),
  47 => 
  array (
    'cat_id' => '47',
    'cat_name' => '奶粉',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '47',
    'name' => '奶粉',
  ),
  6 => 
  array (
    'cat_id' => '6',
    'cat_name' => '天然干货',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '8',
    'goods_num' => 0,
    'level' => 0,
    'id' => '6',
    'name' => '天然干货',
  ),
  58 => 
  array (
    'cat_id' => '58',
    'cat_name' => '干果/果干',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '58',
    'name' => '干果/果干',
  ),
  55 => 
  array (
    'cat_id' => '55',
    'cat_name' => '汤料',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '55',
    'name' => '汤料',
  ),
  59 => 
  array (
    'cat_id' => '59',
    'cat_name' => '豆制品',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '59',
    'name' => '豆制品',
  ),
  56 => 
  array (
    'cat_id' => '56',
    'cat_name' => '豆类',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '56',
    'name' => '豆类',
  ),
  53 => 
  array (
    'cat_id' => '53',
    'cat_name' => '菌菇类',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '53',
    'name' => '菌菇类',
  ),
  60 => 
  array (
    'cat_id' => '60',
    'cat_name' => '腊味',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '60',
    'name' => '腊味',
  ),
  57 => 
  array (
    'cat_id' => '57',
    'cat_name' => '干菜/菜干',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '57',
    'name' => '干菜/菜干',
  ),
  54 => 
  array (
    'cat_id' => '54',
    'cat_name' => '腌干海产',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '54',
    'name' => '腌干海产',
  ),
  7 => 
  array (
    'cat_id' => '7',
    'cat_name' => '精选茗茶',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 0,
    'id' => '7',
    'name' => '精选茗茶',
  ),
  61 => 
  array (
    'cat_id' => '61',
    'cat_name' => '白茶',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '61',
    'name' => '白茶',
  ),
  62 => 
  array (
    'cat_id' => '62',
    'cat_name' => '红茶',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '62',
    'name' => '红茶',
  ),
  63 => 
  array (
    'cat_id' => '63',
    'cat_name' => '绿茶',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '63',
    'name' => '绿茶',
  ),
);
?>